name = "cloudflare-auth-system"
main = "src/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]


#[[d1_databases]]
#binding = "db"			#d1数据库绑定名默认不可修改
#database_name = ""		#d1数据库名字

#[[kv_namespaces]]
#binding = "kv"			#kv绑定名默认不可修改
#id = ""					#kv数据库id

